// Code generated by Kitex v0.6.2. DO NOT EDIT.

package noteservice

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	note "github.com/sjxiang/biz-demo/easy-note/kitex_gen/note"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return noteServiceServiceInfo
}

var noteServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "NoteService"
	handlerType := (*note.NoteService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateNote": kitex.NewMethodInfo(createNoteHandler, newCreateNoteArgs, newCreateNoteResult, false),
		"MGetNote":   kitex.NewMethodInfo(mGetNoteHandler, newMGetNoteArgs, newMGetNoteResult, false),
		"DeleteNote": kitex.NewMethodInfo(deleteNoteHandler, newDeleteNoteArgs, newDeleteNoteResult, false),
		"QueryNote":  kitex.NewMethodInfo(queryNoteHandler, newQueryNoteArgs, newQueryNoteResult, false),
		"UpdateNote": kitex.NewMethodInfo(updateNoteHandler, newUpdateNoteArgs, newUpdateNoteResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "note",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.6.2",
		Extra:           extra,
	}
	return svcInfo
}

func createNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(note.CreateNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(note.NoteService).CreateNote(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *CreateNoteArgs:
		success, err := handler.(note.NoteService).CreateNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateNoteResult)
		realResult.Success = success
	}
	return nil
}
func newCreateNoteArgs() interface{} {
	return &CreateNoteArgs{}
}

func newCreateNoteResult() interface{} {
	return &CreateNoteResult{}
}

type CreateNoteArgs struct {
	Req *note.CreateNoteRequest
}

func (p *CreateNoteArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(note.CreateNoteRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateNoteArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateNoteArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in CreateNoteArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *CreateNoteArgs) Unmarshal(in []byte) error {
	msg := new(note.CreateNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateNoteArgs_Req_DEFAULT *note.CreateNoteRequest

func (p *CreateNoteArgs) GetReq() *note.CreateNoteRequest {
	if !p.IsSetReq() {
		return CreateNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateNoteResult struct {
	Success *note.CreateNoteResponse
}

var CreateNoteResult_Success_DEFAULT *note.CreateNoteResponse

func (p *CreateNoteResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(note.CreateNoteResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateNoteResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateNoteResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in CreateNoteResult")
	}
	return proto.Marshal(p.Success)
}

func (p *CreateNoteResult) Unmarshal(in []byte) error {
	msg := new(note.CreateNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateNoteResult) GetSuccess() *note.CreateNoteResponse {
	if !p.IsSetSuccess() {
		return CreateNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*note.CreateNoteResponse)
}

func (p *CreateNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateNoteResult) GetResult() interface{} {
	return p.Success
}

func mGetNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(note.MGetNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(note.NoteService).MGetNote(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *MGetNoteArgs:
		success, err := handler.(note.NoteService).MGetNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MGetNoteResult)
		realResult.Success = success
	}
	return nil
}
func newMGetNoteArgs() interface{} {
	return &MGetNoteArgs{}
}

func newMGetNoteResult() interface{} {
	return &MGetNoteResult{}
}

type MGetNoteArgs struct {
	Req *note.MGetNoteRequest
}

func (p *MGetNoteArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(note.MGetNoteRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *MGetNoteArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *MGetNoteArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *MGetNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in MGetNoteArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *MGetNoteArgs) Unmarshal(in []byte) error {
	msg := new(note.MGetNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MGetNoteArgs_Req_DEFAULT *note.MGetNoteRequest

func (p *MGetNoteArgs) GetReq() *note.MGetNoteRequest {
	if !p.IsSetReq() {
		return MGetNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MGetNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MGetNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MGetNoteResult struct {
	Success *note.MGetNoteResponse
}

var MGetNoteResult_Success_DEFAULT *note.MGetNoteResponse

func (p *MGetNoteResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(note.MGetNoteResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *MGetNoteResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *MGetNoteResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *MGetNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in MGetNoteResult")
	}
	return proto.Marshal(p.Success)
}

func (p *MGetNoteResult) Unmarshal(in []byte) error {
	msg := new(note.MGetNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MGetNoteResult) GetSuccess() *note.MGetNoteResponse {
	if !p.IsSetSuccess() {
		return MGetNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MGetNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*note.MGetNoteResponse)
}

func (p *MGetNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MGetNoteResult) GetResult() interface{} {
	return p.Success
}

func deleteNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(note.DeleteNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(note.NoteService).DeleteNote(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *DeleteNoteArgs:
		success, err := handler.(note.NoteService).DeleteNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteNoteResult)
		realResult.Success = success
	}
	return nil
}
func newDeleteNoteArgs() interface{} {
	return &DeleteNoteArgs{}
}

func newDeleteNoteResult() interface{} {
	return &DeleteNoteResult{}
}

type DeleteNoteArgs struct {
	Req *note.DeleteNoteRequest
}

func (p *DeleteNoteArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(note.DeleteNoteRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteNoteArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteNoteArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in DeleteNoteArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteNoteArgs) Unmarshal(in []byte) error {
	msg := new(note.DeleteNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteNoteArgs_Req_DEFAULT *note.DeleteNoteRequest

func (p *DeleteNoteArgs) GetReq() *note.DeleteNoteRequest {
	if !p.IsSetReq() {
		return DeleteNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteNoteResult struct {
	Success *note.DeleteNoteResponse
}

var DeleteNoteResult_Success_DEFAULT *note.DeleteNoteResponse

func (p *DeleteNoteResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(note.DeleteNoteResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteNoteResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteNoteResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in DeleteNoteResult")
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteNoteResult) Unmarshal(in []byte) error {
	msg := new(note.DeleteNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteNoteResult) GetSuccess() *note.DeleteNoteResponse {
	if !p.IsSetSuccess() {
		return DeleteNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*note.DeleteNoteResponse)
}

func (p *DeleteNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteNoteResult) GetResult() interface{} {
	return p.Success
}

func queryNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(note.QueryNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(note.NoteService).QueryNote(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *QueryNoteArgs:
		success, err := handler.(note.NoteService).QueryNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryNoteResult)
		realResult.Success = success
	}
	return nil
}
func newQueryNoteArgs() interface{} {
	return &QueryNoteArgs{}
}

func newQueryNoteResult() interface{} {
	return &QueryNoteResult{}
}

type QueryNoteArgs struct {
	Req *note.QueryNoteRequest
}

func (p *QueryNoteArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(note.QueryNoteRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *QueryNoteArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *QueryNoteArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *QueryNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in QueryNoteArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *QueryNoteArgs) Unmarshal(in []byte) error {
	msg := new(note.QueryNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryNoteArgs_Req_DEFAULT *note.QueryNoteRequest

func (p *QueryNoteArgs) GetReq() *note.QueryNoteRequest {
	if !p.IsSetReq() {
		return QueryNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QueryNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QueryNoteResult struct {
	Success *note.QueryNoteResponse
}

var QueryNoteResult_Success_DEFAULT *note.QueryNoteResponse

func (p *QueryNoteResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(note.QueryNoteResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *QueryNoteResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *QueryNoteResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *QueryNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in QueryNoteResult")
	}
	return proto.Marshal(p.Success)
}

func (p *QueryNoteResult) Unmarshal(in []byte) error {
	msg := new(note.QueryNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryNoteResult) GetSuccess() *note.QueryNoteResponse {
	if !p.IsSetSuccess() {
		return QueryNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*note.QueryNoteResponse)
}

func (p *QueryNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QueryNoteResult) GetResult() interface{} {
	return p.Success
}

func updateNoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(note.UpdateNoteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(note.NoteService).UpdateNote(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *UpdateNoteArgs:
		success, err := handler.(note.NoteService).UpdateNote(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateNoteResult)
		realResult.Success = success
	}
	return nil
}
func newUpdateNoteArgs() interface{} {
	return &UpdateNoteArgs{}
}

func newUpdateNoteResult() interface{} {
	return &UpdateNoteResult{}
}

type UpdateNoteArgs struct {
	Req *note.UpdateNoteRequest
}

func (p *UpdateNoteArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(note.UpdateNoteRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateNoteArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateNoteArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateNoteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in UpdateNoteArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateNoteArgs) Unmarshal(in []byte) error {
	msg := new(note.UpdateNoteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateNoteArgs_Req_DEFAULT *note.UpdateNoteRequest

func (p *UpdateNoteArgs) GetReq() *note.UpdateNoteRequest {
	if !p.IsSetReq() {
		return UpdateNoteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateNoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateNoteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateNoteResult struct {
	Success *note.UpdateNoteResponse
}

var UpdateNoteResult_Success_DEFAULT *note.UpdateNoteResponse

func (p *UpdateNoteResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(note.UpdateNoteResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateNoteResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateNoteResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateNoteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in UpdateNoteResult")
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateNoteResult) Unmarshal(in []byte) error {
	msg := new(note.UpdateNoteResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateNoteResult) GetSuccess() *note.UpdateNoteResponse {
	if !p.IsSetSuccess() {
		return UpdateNoteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateNoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*note.UpdateNoteResponse)
}

func (p *UpdateNoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateNoteResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateNote(ctx context.Context, Req *note.CreateNoteRequest) (r *note.CreateNoteResponse, err error) {
	var _args CreateNoteArgs
	_args.Req = Req
	var _result CreateNoteResult
	if err = p.c.Call(ctx, "CreateNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MGetNote(ctx context.Context, Req *note.MGetNoteRequest) (r *note.MGetNoteResponse, err error) {
	var _args MGetNoteArgs
	_args.Req = Req
	var _result MGetNoteResult
	if err = p.c.Call(ctx, "MGetNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteNote(ctx context.Context, Req *note.DeleteNoteRequest) (r *note.DeleteNoteResponse, err error) {
	var _args DeleteNoteArgs
	_args.Req = Req
	var _result DeleteNoteResult
	if err = p.c.Call(ctx, "DeleteNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryNote(ctx context.Context, Req *note.QueryNoteRequest) (r *note.QueryNoteResponse, err error) {
	var _args QueryNoteArgs
	_args.Req = Req
	var _result QueryNoteResult
	if err = p.c.Call(ctx, "QueryNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateNote(ctx context.Context, Req *note.UpdateNoteRequest) (r *note.UpdateNoteResponse, err error) {
	var _args UpdateNoteArgs
	_args.Req = Req
	var _result UpdateNoteResult
	if err = p.c.Call(ctx, "UpdateNote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
