// Code generated by Kitex v0.6.2. DO NOT EDIT.
package noteservice

import (
	server "github.com/cloudwego/kitex/server"
	note "github.com/sjxiang/biz-demo/easy-note/kitex_gen/note"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler note.NoteService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
