/*
 * Copyright 2023 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package comment

import (
	"context"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/sjxiang/biz-demo/tiktok_demo/pkg/errno"
	"github.com/sjxiang/biz-demo/tiktok_demo/pkg/utils"

	comment "github.com/sjxiang/biz-demo/tiktok_demo/biz/model/interact/comment"
	comment_service "github.com/sjxiang/biz-demo/tiktok_demo/biz/service/comment"
)

// CommentAction user send comment of video.
//
// @router /douyin/comment/action/ [POST]
func CommentAction(c *gin.Context) {
	var (
		err error
		req comment.DouyinCommentActionRequest
	)

	err = c.ShouldBindJSON(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(http.StatusOK, comment.DouyinCommentActionResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
	}

	comment_, err := comment_service.NewCommentService(context.Background(), c).AddNewComment(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(http.StatusOK, comment.DouyinCommentActionResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
	}

	c.JSON(http.StatusOK, comment.DouyinCommentActionResponse{
		StatusCode: errno.SuccessCode,
		StatusMsg:  errno.SuccessMsg,
		Comment:    comment_,
	})
}

// CommentList get all comments on a video in reverse chronological order.
//
// @router /douyin/comment/list/ [GET]
func CommentList(c *gin.Context) {
	var err error
	var req comment.DouyinCommentListRequest
	
	err = c.ShouldBindJSON(&req)
	if err != nil {
		c.String(http.StatusBadRequest, err.Error())
	}

	resp, err := comment_service.NewCommentService(context.Background(), c).CommentList(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(http.StatusOK, comment.DouyinCommentActionResponse{
			StatusCode: resp.StatusCode,
			StatusMsg:  resp.StatusMsg,
		})
		return
	}

	c.JSON(http.StatusOK, resp)
}
